export * from "./Login/Form/Form"
export * from "./Login/ImgComponent/ImgComponent"
export * from "./Relatorios/Relatorios"
export * from "./Turmas/CriarTurma/CriarTurma"
export * from "./Turmas/TurmaCard/TurmaCard"
export * from "./TurmaUnica/CriaProf/CriaProf"
export * from "./TurmaUnica/CriaAluno/CriaAluno"
export * from "./TurmaUnica/AlunoList/AlunoList"
